happy/config/routes.rb
Rails.application.routes.draw do
  get 'gossip/index'

 root 'gossips#index'
 
 resources:gossips 
end

happy/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

happy/app/models/gossip.rb
class Gossip < ApplicationRecord
     validates :anonymous_author, :content, presence: true,
                    length: { minimum: 4 }
end

happy/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

happy/app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
	
def new 
		@new_gossip=Gossip.new
end


def edit 
    @gossip = Gossip.find(params[:id])
  end

  def update 
    @gossip = Gossip.find(params[:id])
    if @gossip.update(gossip_params)
      redirect_to @gossip
      else 
      render 'edit'
 end
end

def create
  @gossip = Gossip.create(gossip_params)
  	if @gossip.save
  		redirect_to @gossip
  	else 
  		render 'new'
end 
end


def show
  @gossip = Gossip.find(params[:id])
end

def index
  @gossips=Gossip.all
 end

def destroy
    @gossip = Gossip.find(params[:id])
    @gossip.destroy
  redirect_to gossips_path
  end

private
   def gossip_params
   params.require(:gossip).permit(:anonymous_author, :content)
  end

end

happy/app/helpers/application_helper.rb
module ApplicationHelper
end

happy/app/helpers/gossips_helper.rb
module GossipsHelper
end

happy/app/helpers/home_helper.rb
module HomeHelper
end

happy/app/views/gossips/_form.html.erb
<%= label_tag 'anonymous_author', 'auteur' %>
	<%= text_field_tag 'anonymous_author' %>

	<%= label_tag 'content', 'ton gossip' %>
	<%= text_field_tag 'author' %>

happy/app/views/gossips/edit.html.erb
<h1>Gossips#edit</h1>

<%= form_tag gossip_path(@gossip), method: :put do %>

<%= render 'form' %> 

	<%= submit_tag "modifies ton gossip"%>
<% end %>

happy/app/views/gossips/index.html.erb
<h1>Listes des gossips</h1>
 
<table>
  <tr>
    <th>author</th>
    <th>gossip</th>
  </tr>
 
  <% @gossips.each do |gossip| %>
    <tr>
      <td><%= gossip.anonymous_author%></td>
      <td><%= gossip.content %></td>
      <td><%= link_to 'Montrer le gossip', gossip_path(gossip) %></td>
      %></td>
      <td><%= link_to 'Editer le gossip', edit_gossip_path(gossip) %></td>
      <td><%= link_to 'Destroy', gossip_path(gossip),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>



<p> <%= link_to("Nouveau gossip", new_gossip_path) %> </p>

happy/app/views/gossips/new.html.erb
<h1> Creer un gossip</h1>

<%= form_tag (gossips_path) do %>

	<%= render 'form' %> 

	<%= submit_tag "Poster un gossip"%>
<% end %>

happy/app/views/gossips/show.html.erb
<h2><%= @gossip.anonymous_author %></h2>
<p><%= @gossip.content %></p>


<p> <%= link_to("Editer le gossip", edit_gossip_path) %></p>

<p> <%= link_to("revenir à la liste des gossip", gossips_path) %></p>

<p><%= link_to 'Clique pour détruire', @gossip, method: :delete %></p>

happy/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipProject</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>